<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\tuning\**\*.csproj" ReferenceOutputAssembly="false">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Codebelt.Extensions.BenchmarkDotNet.Console" />
  </ItemGroup>

</Project>
